[tool.poetry]
name = "mlb_fan_highlights" 
version = "0.1.0"
description = ""
authors = ["Adedoyinsola Ogungbesan <jdmasciano2@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
google-cloud-pubsub = "^2.27.0" 
google-cloud-storage = "^2.3.6" 
apache-beam = "^2.46.0" 

[tool.poetry.dev-dependencies]
pytest = "^7.3.1" 

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"